all: CacheSimulator.java Functions.java
	javac CacheSimulator.java Functions.java

test1: 
	java CacheSimulator input.txt

test2: 
	java CacheSimulator input2.txt

test3:
	java CacheSimulator input3.txt
	
test4:
	java CacheSimulator input4.dat

test5:
	java CacheSimulator input5.txt

test6:
	java CacheSimulator input6.txt
	
clean:
	rm -f *.class 
