CREATE TABLE BASE_PRICE(
    PRICE_ID INTEGER(10) NOT NULL,
    SIZE VARCHAR(20) NOT NULL,
    CRUST VARCHAR(30) NOT NULL,
    PRICE DOUBLE NOT NULL,
    COST DOUBLE NOT NULL,
    PRIMARY KEY (PRICE_ID)
);

CREATE TABLE TOPPINGS(
    NAME VARCHAR(30) NOT NULL,
    PRICE DOUBLE NOT NULL,
    COST_PER_UNIT DOUBLE NOT NULL,
    INVENTORY INTEGER(3),
    P_SMALL DOUBLE,
    P_MEDIUM DOUBLE,
    P_LARGE DOUBLE,
    P_X_LARGE DOUBLE,
    PRIMARY KEY (NAME)
);

CREATE TABLE ORDERS(
    ORDER_ID INT NOT NULL,
    PRIMARY KEY (ORDER_ID)
);

CREATE TABLE PIZZA(
    PIZZA_ID INTEGER NOT NULL,
    ORDER_STATUS VARCHAR(40),
    TIME_STAMP TIMESTAMP,
    PRICE_ID INTEGER(10) NOT NULL,
    ORDER_ID INTEGER(10) NOT NULL,
    CUSTOMER_PRICE DOUBLE NOT NULL,
    BUSINESS_COST DOUBLE NOT NULL,
    PRIMARY KEY (PIZZA_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (PRICE_ID) REFERENCES BASE_PRICE(PRICE_ID)
);

CREATE TABLE HAS_TOPPINGS(
    PIZZA_ID INT NOT NULL,
    TOPPING_NAME VARCHAR(30) NOT NULL,
    DOUBLE_AMOUNT VARCHAR(4),
    PRIMARY KEY (PIZZA_ID, TOPPING_NAME),
    FOREIGN KEY (TOPPING_NAME) REFERENCES TOPPINGS(NAME)
);

CREATE TABLE DISCOUNTS(
    DISCOUNT_ID INTEGER(2) NOT NULL,
    NAME VARCHAR(50),
    PERCENT_OFF INTEGER,
    DOLLAR_OFF DOUBLE,
    PRIMARY KEY (DISCOUNT_ID)
);

CREATE TABLE PIZZA_DISCOUNTS(
    PIZZA_ID INTEGER(10) NOT NULL,
    DISCOUNT_ID INTEGER(10) NOT NULL,
    PRIMARY KEY (PIZZA_ID, DISCOUNT_ID),
    FOREIGN KEY (PIZZA_ID) REFERENCES PIZZA(PIZZA_ID),
    FOREIGN KEY (DISCOUNT_ID) REFERENCES DISCOUNTS(DISCOUNT_ID)
);

CREATE TABLE ORDER_DISCOUNTS(
    ORDER_ID INTEGER(10) NOT NULL,
    DISCOUNT_ID INTEGER(10) NOT NULL,
    PRIMARY KEY (ORDER_ID, DISCOUNT_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (DISCOUNT_ID) REFERENCES DISCOUNTS(DISCOUNT_ID)
);

CREATE TABLE CUSTOMER(
    CUSTOMER_ID INTEGER(10) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(100),
    PHONE_NUMBER VARCHAR(12),
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE DINE_IN(
    ORDER_ID INTEGER(10) NOT NULL,
    TABLE_NUMBER INTEGER(2),
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);

CREATE TABLE SEAT_NUMBER(
    SEAT_ORDER_ID INTEGER(10) NOT NULL,
    SEAT_NUMBER INTEGER(2) NOT NULL,
    PRIMARY KEY (SEAT_ORDER_ID, SEAT_NUMBER),
    FOREIGN KEY (SEAT_ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);

CREATE TABLE DELIVERY(
    ORDER_ID INTEGER(10) NOT NULL,
    CUSTOMER_ID INTEGER(10) NOT NULL,
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE PICK_UP(
    ORDER_ID INTEGER(10) NOT NULL,
    CUSTOMER_ID INTEGER(10) NOT NULL,
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);
